In [3]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [4]:
env = gym.make('FrozenLake-v1', render_mode='ansi')

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

rewards_all_episodes = []

In [6]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()[0]
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, truncated, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        state = new_state
        rewards_current_episode += reward

        if done:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

/home/light/.local/lib/python3.11/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [7]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.04100000000000003
2000 :  0.22000000000000017
3000 :  0.3840000000000003
4000 :  0.5480000000000004
5000 :  0.6450000000000005
6000 :  0.6690000000000005
7000 :  0.7100000000000005
8000 :  0.6980000000000005
9000 :  0.7060000000000005
10000 :  0.6840000000000005


********Q-table********

[[0.58999266 0.50836594 0.50929478 0.5063794 ]
 [0.36800789 0.33594605 0.29294478 0.51667101]
 [0.4123049  0.43851821 0.42852305 0.47566252]
 [0.34810996 0.37675296 0.40241891 0.45237609]
 [0.62608101 0.33782777 0.42653519 0.36009232]
 [0.         0.         0.         0.        ]
 [0.18232058 0.15156132 0.27456929 0.1541735 ]
 [0.         0.         0.         0.        ]
 [0.2247937  0.37965305 0.41091404 0.66671616]
 [0.41033416 0.68785775 0.48811462 0.33239892]
 [0.69031905 0.391077   0.40923055 0.34559581]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.39976205 0.59302801 0.76250002 

In [8]:
# Watch our agent play Frozen Lake by playing the best action
# from each state according to the Q-table

for episode in range(3):
    state = env.reset()[0]
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        print(env.render())
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state, reward, done, truncated, info = env.step(action)

        if done:
            clear_output(wait=True)
            print(env.render())
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
                break

        state = new_state

env.close()


  (Left)
SFFF
FHFH
FFFH
HFFG

****You fell through a hole!****
